### ISSUE TITLE
It says playing song but never plays

### ISSUE THREAD

**Issue by Raul824** [cosmosis14/custom-youtube#3]
The skill was working flawlessly until suddenly it stopped working.
I cannot see any issues in cloud watch logs of lambda function as it is returning the uri but the songs is not playing on alexa.

I tried test from alexa as well but I cannot see any errors, could you suggest me any troubleshooting steps.

I tried re-deploying the lambda function and it gave yt-dl update required which I did and now it is back to original error where it says playing and then never plays the songs.

**Comment by CalColson** [comment]
unfortunately i've ditched my alexa for google, or i would work on fixing this.

the last time it broke this way though, it did have to do with updating ytdl-core [(see here)](https://github.com/cosmosis14/custom-youtube/issues/1#issuecomment-748515927).

i suggest seeing if you can fetch and play a test song, using code similar to the ytdlTest.js in the tests folder. if that doesn't work, then it's a problem with ytdl.

best of luck!

**Comment by Raul824** [comment]
thanks I updated your skill to support aws-sdk3 and put new ytdl-core.
